name: app
description: POA(Power Of Arts)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# 의존성 패키지 추가 (pub.dev)
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6 # 2023.05.18. 상태관리 추가
  dio: ^5.1.2 # 2023.05.18. http 요청
  flutter_secure_storage: ^8.0.0 # 2023.05.18. 민감 정보 저장

# dev 모드 패키지 추가 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # 이미지
    - assets/icons/ # 아이콘

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 100
