name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6 
  riverpod_annotation: ^2.1.1
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0 
  carousel_slider: ^4.2.1
  json_annotation: ^4.8.1
  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 100